### ISSUE TITLE
Netty Decoder doesn't work with fragmentation

### ISSUE THREAD

**Issue by wburns** [galderz/scala-client#1]
Looking at https://github.com/galderz/scala-client/blob/master/src/main/scala/org/infinispan/scala/hotrod/impl/Decoder20.scala, it is nice how it uses scala for yield clause.  Unfortunately this won't work if the bytes are fragmented.  If for example the magic byte was read but the id isn't present the buffer read index is set to after magic.  Then when the decode is tried again the magic value is read from the id byte.  You probably want to reset the read buffer to the very beginning on a miss or store state so you don't have to read them again.

**Comment by galderz** [comment]
Makes sense, thanks for the heads up. This is just a prototype I wrote a while back and have not really worked on it since :)
